# Generated by Django 4.1 on 2022-09-12 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='count',
            new_name='amount',
        ),
    ]
