# Generated by Django 4.1 on 2022-09-12 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_count_cartitem_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='image',
        ),
        migrations.AddField(
            model_name='item',
            name='imageSrc',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
