# Generated by Django 4.1 on 2022-09-15 14:20

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MyWatchList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("watched", models.BooleanField(default=False)),
                ("title", models.CharField(max_length=100)),
                (
                    "rating",
                    models.DecimalField(
                        decimal_places=2,
                        default=1,
                        max_digits=3,
                        validators=[
                            django.core.validators.MaxValueValidator(5),
                            django.core.validators.MinValueValidator(1),
                        ],
                    ),
                ),
                (
                    "release_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("review", models.TextField()),
            ],
        ),
    ]
