# Generated by Django 4.1 on 2022-09-26 09:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("mywatchlist", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mywatchlist",
            name="release_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
